name: Deploy to Replicate

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install Cog
      run: |
        sudo curl -o /usr/local/bin/cog -L https://github.com/replicate/cog/releases/latest/download/cog_Linux_x86_64
        sudo chmod +x /usr/local/bin/cog
        
    - name: Login to Replicate
      env:
        REPLICATE_API_TOKEN: ${{ secrets.REPLICATE_API_TOKEN }}
      run: echo $REPLICATE_API_TOKEN | cog login --token-stdin
      
    - name: Push to Replicate
      env:
        REPLICATE_MODEL_NAME: ${{ secrets.REPLICATE_MODEL_NAME }}
      run: cog push $REPLICATE_MODEL_NAME 